### ISSUE TITLE
Check Python 3.11

### ISSUE THREAD

**Issue by kwinkunks** [scienxlab/redflag#15]

**Comment by Bchass** [comment]
pytest silently fails with 3.11: https://github.com/pytest-dev/pytest-cov/issues/564

Went through some of the basic usage of redflag with 3.11 and didn't run into any issues that I could see. But this doesn't mean much until pytest supports 3.11.

**Comment by kwinkunks** [comment]
Thank you for looking at this -- much appreciated.

**Comment by kwinkunks** [comment]
Tests are now passing against Python 3.11 :tada:

**Comment by cancan101** [comment]
How curious how you ended up getting tests to pass on 3.11?
