### ISSUE TITLE
`utils.docstring_from()` decorator does not work

### ISSUE THREAD

**Issue by kwinkunks** [scienxlab/redflag#83]
The decorator does no do what it should, which is copy the docstring from the original function to (say) the accessor. See disabled test in `test_pandas.py`

**Comment by YellowFoxH4XOR** [comment]
Hey @kwinkunks, I went through the code and found the copying doc string inside the wrapper function won't work as it will only be applied when the wrapper function is called (i.e. wrapper() which will then do the copy and return the actual wrapped function. It will be better to just copy that to the wrapper function object. I have raised a PR for the same

**Comment by kwinkunks** [comment]
Solved by 5eb9b45ad3e5915133ad5f37b45bdabdf9091717

Thank you @YellowFoxH4XOR 👍
