### ISSUE TITLE
Problem installing `[dev]` option

### ISSUE THREAD

**Issue by jsheunis** [scienxlab/redflag#90]
I'm installing via `pip` in a virtual environment on macOS:

```
> pip install redflag[dev]
zsh: no matches found: redflag[dev]
```

On the other hand `pip install redflag` works fine.

---
Ping https://github.com/openjournals/joss-reviews/issues/6065

**Comment by kwinkunks** [comment]
Good catch! I think `zsh` interprets the option as regex, so you have to do `pip install "reflag[dev]"`, with the quotes. And I think that works with most other shells too.

Updated docs with [3895094](https://github.com/scienxlab/redflag/commit/38950949409312977b0acabe0da67702e81ebeaf)
