### ISSUE TITLE
CI testing environment

### ISSUE THREAD

**Issue by jsheunis** [scienxlab/redflag#92]
I see the CI only runs on ubuntu: https://github.com/scienxlab/redflag/blob/main/.github/workflows/build-test.yml

I wouldn't say its absolutely necessary, but it would probably be a good idea to run tests on all major operating systems. If not, I suggest stating that in the documentation.

---
Ping https://github.com/openjournals/joss-reviews/issues/6065

**Comment by kwinkunks** [comment]
Great suggestion, thank you.

Done in [c52d3ce](https://github.com/scienxlab/redflag/commit/c52d3ceafb3f57c05d1c6fa51e7b28390d531f6a)
