### ISSUE TITLE
Lengthy one-page API docs

### ISSUE THREAD

**Issue by jsheunis** [scienxlab/redflag#93]
The Python API documentation is quite lengthy for a single page (https://scienxlab.org/redflag/redflag.html#), and requires lots of scrolling / searching to find specific content. I suggest splitting it up into one page per module.

---
Ping https://github.com/openjournals/joss-reviews/issues/6065

**Comment by kwinkunks** [comment]
Great idea, I need to learn more about the `apidoc` plugin.

Fixed in 046d75812abc87b794e320067aa44a07006bb941
