### ISSUE TITLE
Minimal context in docs

### ISSUE THREAD

**Issue by jsheunis** [scienxlab/redflag#94]
The docs contain a single paragraph explaining the context within which this package operates: https://scienxlab.org/redflag/index.html

I think it would make sense to provide a bit more information to position the software within the context of the ML field so that users can develop a more intuitive understanding of its benefits and use cases. Relatedly, the JOSS checklist states:

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

This is covered nicely in the JOSS paper itself, and perhaps some of this content can be worked into the docs. I actually like the current single paragraph intro in the docs index page before jumping into the quickstart, so perhaps a more detailed overview can be provided on a separate page and referenced from the index page.

Overall, the docs are great. I appreciate the attention given to this. Also, +1 on Furo :)

---
Ping https://github.com/openjournals/joss-reviews/issues/6065

**Comment by kwinkunks** [comment]
Thanks for the kind words, appreciated.

Totally agree that more scene-setting was needed -- I often look for this myself in other packages. I've tried to address this with a new 'What is redflag?' page in the docs. I have self-plagiarized it from the draft paper -- I hope that's okay? Happy to re-word if it seems like too much of a shortcut.

Proposed fix in a525174aa6937c351b871a9053904fbfc279c57f
